"""initial migration

Revision ID: 667916612719
Revises: a9289cf3bac2
Create Date: 2021-04-07 12:35:14.126350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667916612719'
down_revision = 'a9289cf3bac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###
